steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gcpal-409321/ads-gen', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'no-design', '--image', 'gcr.io/gcpal-409321/ads-gen', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images: ['gcr.io/gcpal-409321/ads-gen']
